services:
    backoffice_api.background_event_builder:
        class: Ortofit\Bundle\BackOfficeAPIBundle\EventBuilder\OffHoursEventBuilder
        arguments: ["%calendar_off_hours_color%"]
    backoffice_api.default_background_event_builder:
        class: Ortofit\Bundle\BackOfficeAPIBundle\EventBuilder\DefaultOffHoursEventBuilder
        arguments: ["%calendar_off_hours_color%"]

    backoffice_api.event_service:
        class: Ortofit\Bundle\BackOfficeAPIBundle\EventService\EventService
        arguments: ["@ortofit_back_office.schedule_manage", "@backoffice_api.background_event_builder", "@backoffice_api.default_background_event_builder"]
        calls:
            - [setDefaultOffHoursData, ["%default_off_hours%"]]
