parameters:
    calendar_off_hours_color: "#222D32"
    default_off_hours:
        1:
            -
                start:    "09:00"
                end:      "10:00"
                dow:      [1,2,3,4,5,6]
            -
                start:    "19:00"
                end:      "20:00"
                dow:      [1,2,3,4,5,6]
            -
                start:    "15:00"
                end:      "20:00"
                dow:      [0]
        2:
            -
                start:    "09:00"
                end:      "10:00"
                dow:      [1,2,3,4,5,6]
            -
                start:    "19:00"
                end:      "20:00"
                dow:      [1,2,3,4,5,6]
            -
                start:    "15:00"
                end:      "20:00"
                dow:      [0]