ortofit_back_office_front:
    resource: "@OrtofitBackOfficeFrontBundle/Resources/config/routing.yml"
    prefix:   /

ortofit_back_office_api:
    resource: "@OrtofitBackOfficeAPIBundle/Resources/config/routing.yml"
    prefix:   /api

ortofit_sing_up:
    resource: "@OrtofitSingUpBundle/Resources/config/routing.yml"
    prefix:   /sing_up

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
