parameters:
    not_active_hours:
        - { start: '09:00', end: '10:00', dow: [1,2,3,4,5,6], color: '#222D32', overlap: true, rendering: 'background' }
        - { start: '19:00', end: '20:00', dow: [1,2,3,4,5,6], color: '#222D32', overlap: true, rendering: 'background' }
        - { start: '15:00', end: '20:00', dow: [0], color: '#222D32', overlap: true, rendering: 'background'}
    work_hours:
        - { start: 9,  end: 15 }
        - { start: 10, end: 19 }
        - { start: 10, end: 19 }
        - { start: 10, end: 19 }
        - { start: 10, end: 19 }
        - { start: 10, end: 19 }
        - { start: 10, end: 19 }
