# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        back_office:
            pattern: ^/(admin)|(api)
            form_login:
                provider: fos_userbundle
                #csrf_provider: security.csrf.token_manager
                check_path: /admin/login_check
                login_path: /login
                default_target_path: admin_panel
                #csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4

            logout:
                path:   logout
                target: login_route

    access_control:
        - { path: ^/(admin)|(api)/.*/.*/.*/.*, role: ROLE_ADMIN }

