admin_panel:
    path:     /admin
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:index }
login_route:
    path:     /login
    defaults: { _controller: OrtofitBackOfficeBundle:Login:login }
logout:
    path:     /admin/logout
    defaults: { _controller: OrtofitBackOfficeBundle:Login::logout }
login_check:
    path:     /admin/login_check
    defaults: { _controller: OrtofitBackOfficeBundle:Login:securityCheck }
#backend_manage_get:
#    path:     /admin/get/{entityName}
#    defaults: { _controller: OrtofitBackOfficeBundle:Manage:get }
#backend_manage_create:
#    path:     /admin/create/{entityName}
#    defaults: { _controller: OrtofitBackOfficeBundle:Manage:create }
#backend_manage_update:
#    path:     /admin/update/{entityName}
#    defaults: { _controller: OrtofitBackOfficeBundle:Manage:update }
#backend_manage_remove:
#    path:     /admin/remove/{entityName}
#    defaults: { _controller: OrtofitBackOfficeBundle:Manage:remove }
#backend_manage_find:
#    path:     /admin/find/{entityName}
#    defaults: { _controller: OrtofitBackOfficeBundle:Manage:find }
#backend_manage_entity_index:
#    path:     /admin/entity
#    defaults: { _controller: OrtofitBackOfficeBundle:Entity:index }

backendoffice_client:
    path:     /admin/client
    defaults: { _controller: OrtofitBackOfficeBundle:Client:index }
backendoffice_client_form:
    path:     /admin/client/form
    defaults: { _controller: OrtofitBackOfficeBundle:Client:form }
backendoffice_client_update:
    path:     /admin/client/update
    defaults: { _controller: OrtofitBackOfficeBundle:Client:update }
backendoffice_client_create:
    path:     /admin/client/create
    defaults: { _controller: OrtofitBackOfficeBundle:Client:create }
backendoffice_client_find:
    path:     /admin/client/find
    defaults: { _controller: OrtofitBackOfficeBundle:Client:find }


backendoffice_person:
    path:     /admin/person
    defaults: { _controller: OrtofitBackOfficeBundle:Person:index }

backendoffice_person_form:
    path:     /admin/person/form
    defaults: { _controller: OrtofitBackOfficeBundle:Person:form }
backendoffice_person_create:
    path:     /admin/person/create
    defaults: { _controller: OrtofitBackOfficeBundle:Person:create }
backendoffice_person_update:
    path:     /admin/person/update
    defaults: { _controller: OrtofitBackOfficeBundle:Person:update }

backendoffice_diagnosis_form:
    path:     /admin/diagnosis/form
    defaults: { _controller: OrtofitBackOfficeBundle:Diagnosis:form }
backendoffice_diagnosis_create:
    path:     /admin/diagnosis/create
    defaults: { _controller: OrtofitBackOfficeBundle:Diagnosis:create }
backendoffice_diagnosis_update:
    path:     /admin/diagnosis/update
    defaults: { _controller: OrtofitBackOfficeBundle:Diagnosis:update }

backendoffice_appointment_get_form:
    path:     /admin/app/form
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:form }
backendoffice_appointment_create:
    path:     /admin/app/create
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:create }
backendoffice_appointment_update:
    path:     /admin/app/update
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:update }
backendoffice_appointment_delete:
    path:     /admin/app/delete
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:delete }

backendoffice_appointment_get_app:
    path:     /admin/app/get
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:getApp }
backendoffice_appointment_pre_app:
    path:     /admin/app/pre
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:preOrder }
backendoffice_appointment_work_hours:
    path:     /admin/app/work_hours
    defaults: { _controller: OrtofitBackOfficeBundle:Appointment:workHours }

acme_demo_user_all:
    path:  /admin/users
    defaults: { _controller: OrtofitBackOfficeBundle:DoctorRest:users, _format: ~ }
    requirements:
        _method: GET
