services:
    ortofit_back_office.entity_manager_olm:
        class: Ortofit\Bundle\BackOfficeBundle\OLM\EntityManagerOLM
    ortofit_back_office.appointment_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\AppointmentManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.appointment_reason_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\AppointmentReasonManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }

    ortofit_back_office.client_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ClientManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.reason_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ReasonManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }

    ortofit_back_office.client_direction_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ClientDirectionManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }

    ortofit_back_office.schedule_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ScheduleManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }

    ortofit_back_office.client_source_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ClientDirectionManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.client_country_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\CountryManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.client_diagnosis_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\DiagnosisManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.client_family_status_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\FamilyStatusManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.order_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\OrderManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.person_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\PersonManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.service_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ServiceManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.office_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\OfficeManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.person_service_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\PersonServiceManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.app_reminder_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\AppReminderManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
    ortofit_back_office.app_insole_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\InsoleManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }

    ortofit_back_office.app_insole_type_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\InsoleTypeManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }

    ortofit_back_office.app_service_group_manage:
        class: Ortofit\Bundle\BackOfficeBundle\EntityManager\ServiceGroupManager
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: ortofit_back_office.entity_manager_olm }
