admin_panel:
    path:     /admin
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Appointment:index }
login_route:
    path:     /login
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Login:login }
logout:
    path:     /admin/logout
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Login::logout }
login_check:
    path:     /admin/login_check
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Login:securityCheck }
#backend_manage_get:
#    path:     /admin/get/{entityName}
#    defaults: { _controller: OrtofitBackOfficeFrontBundle:Manage:get }
#backend_manage_create:
#    path:     /admin/create/{entityName}
#    defaults: { _controller: OrtofitBackOfficeFrontBundle:Manage:create }
#backend_manage_update:
#    path:     /admin/update/{entityName}
#    defaults: { _controller: OrtofitBackOfficeFrontBundle:Manage:update }
#backend_manage_remove:
#    path:     /admin/remove/{entityName}
#    defaults: { _controller: OrtofitBackOfficeFrontBundle:Manage:remove }
#backend_manage_find:
#    path:     /admin/find/{entityName}
#    defaults: { _controller: OrtofitBackOfficeFrontBundle:Manage:find }
#backend_manage_entity_index:
#    path:     /admin/entity
#    defaults: { _controller: OrtofitBackOfficeFrontBundle:Entity:index }

bf_client:
    path:     /admin/client
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Client:index }
bf_client_form:
    path:     /admin/client/form
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Client:form }


bf_person:
    path:     /admin/person
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Person:index }

bf_person_form:
    path:     /admin/person/form
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Person:form }


bf_diagnosis_form:
    path:     /admin/diagnosis/form
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Diagnosis:form }


bf_app_get_form:
    path:     /admin/app/form
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Appointment:form }
bf_app_view_app:
    path:     /admin/app/view
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Appointment:viewApp }

bf_app_reschedule:
    path:     /admin/app/reschedule/{appId}
    defaults: { _controller: OrtofitBackOfficeFrontBundle:Appointment:reschedule }

bf_app_order_process:
    path: /admin/app_order/process
    defaults: { _controller: OrtofitBackOfficeFrontBundle:AppOrder:process }

bf_remind_index:
    path: /admin/remind
    defaults: { _controller: OrtofitBackOfficeFrontBundle:AppReminder:index }