services:
    bf.state_choose_persone:
        class: Ortofit\Bundle\BackOfficeFrontBundle\Order\State\ChoosePerson
        arguments: ["OrtofitBackOfficeFrontBundle:Order:choosePerson.html.twig", "@request_stack", "@ortofit_back_office.appointment_manage"]
    bf.state_persone:
        class: Ortofit\Bundle\BackOfficeFrontBundle\Order\State\PersonState
        arguments: ["OrtofitBackOfficeFrontBundle:Order:newPerson.html.twig", "@request_stack", "@ortofit_back_office.appointment_manage"]
        calls:
            - [setPersonManager, ["@ortofit_back_office.person_manage"]]
            - [setFamilyStatusManager, ["@ortofit_back_office.client_family_status_manage"]]

    bf.state_diagnosis:
        class: Ortofit\Bundle\BackOfficeFrontBundle\Order\State\DiagnosisState
        arguments: ["OrtofitBackOfficeFrontBundle:Order:diagnosisPerson.html.twig", "@request_stack", "@ortofit_back_office.appointment_manage"]
        calls:
            - [setPersonManager, ["@ortofit_back_office.person_manage"]]
            - [setDiagnosisManager, ["@ortofit_back_office.client_diagnosis_manage"]]
    bf.state_service:
        class: Ortofit\Bundle\BackOfficeFrontBundle\Order\State\ServiceState
        arguments: ["OrtofitBackOfficeFrontBundle:Order:serviceState.html.twig", "@request_stack", "@ortofit_back_office.appointment_manage"]
        calls:
            - [setPersonServiceManager, ["@ortofit_back_office.person_service_manage"]]
            - [setServiceManager, ["@ortofit_back_office.service_manage"]]
            - [setPersonManager, ["@ortofit_back_office.person_manage"]]
            - [setAppReminderManager, ["@ortofit_back_office.app_reminder_manage"]]

    bf.flow_order:
        class: Ortofit\Bundle\BackOfficeFrontBundle\Order\Flow\OrderFlow
        arguments: ["@session", "@templating.engine.twig"]
        calls:
            - [addState, ["@bf.state_choose_persone"]]
            - [addState, ["@bf.state_persone"]]
            - [addState, ["@bf.state_diagnosis"]]
            - [addState, ["@bf.state_service"]]

    bf.app_model_provider:
        class: Ortofit\Bundle\BackOfficeFrontBundle\ModelProvider\RequestModelProvider\AppointmentModelProvider
        arguments: ["@request_stack"]

    bf.app_view_model_provider:
        class: Ortofit\Bundle\BackOfficeFrontBundle\ModelProvider\RequestModelProvider\AppointmentViewModelProvider
        arguments: ["@request_stack"]
        calls:
            - [setGroupManager, ["@fos_user.group_manager"]]
            - [setAppManager, ["@ortofit_back_office.appointment_manage"]]
            - [setServiceManager, ["@ortofit_back_office.service_manage"]]
            - [setDirectionManager, ["@ortofit_back_office.client_direction_manage"]]
            - [setOfficeManager, ["@ortofit_back_office.office_manage"]]
            - [setCountryManager, ["@ortofit_back_office.client_country_manage"]]

