services:
    ortofit_stat.request_manager:
        class: Ortofit\Bundle\StatBundle\Service\StatRequestManager
        arguments: ["@request_stack", "@rsmakota_utility.date_range_service"]

    ortofit_stat.app_indicator:
        class: Ortofit\Bundle\StatBundle\Indicator\ApplicationIndicator
        arguments: ["@ortofit_back_office.appointment_manage", "@rsmakota_utility.date_range_service"]

    ortofit_stat.indicator_service:
        class: Ortofit\Bundle\StatBundle\Service\IndicatorService
        calls:
            - [add, ["@ortofit_stat.app_indicator"]]
