ortofit_sing_up_index:
    path:     /index/{appId}
    defaults: { _controller: OrtofitSingUpBundle:SingUp:index }

ortofit_sing_up_process:
    path:     /process
    defaults: { _controller: OrtofitSingUpBundle:SingUp:process }