services:
#    ortofit_sing_up.example:
#        class: Ortofit\Bundle\SingUpBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ortofit_sing_up.sing_up_security:
        class: Ortofit\Bundle\SingUpBundle\Security\SingUpSecurity
        arguments: [@session]

    ortofit_sing_up.mail_manager:
        class: Ortofit\Bundle\SingUpBundle\Notify\NotifyMailManager
        arguments: [@swiftmailer.mailer.default]
        calls:
            - [setFrom, [%mailer_from%]]
            - [setTo, [%mailer_to%]]

    ortofit_sing_up.order_listener:
        class: Ortofit\Bundle\SingUpBundle\Listener\OrderListener
        arguments: [@ortofit_sing_up.mail_manager]
        tags:
            - { name: kernel.event_listener, event: sing_up.create_order_event, method: onCreate }

    ortofit_sing_up.client_manager:
        class: Ortofit\Bundle\SingUpBundle\Service\ClientManager
        arguments: [@doctrine.orm.entity_manager]

    ortofit_sing_up.application_manager:
        class: Ortofit\Bundle\SingUpBundle\Service\ApplicationManager
        arguments: [@doctrine.orm.entity_manager]

    ortofit_sing_up.order_manager:
        class: Ortofit\Bundle\SingUpBundle\Service\OrderManager
        arguments: [@doctrine.orm.entity_manager, @ortofit_sing_up.client_manager]
        calls:
            - [setEventDispatcher, [@event_dispatcher]]

    ortofit_sing_up.application_flow:
        class: Ortofit\Bundle\SingUpBundle\Application\ApplicationFlow
        arguments: [@ortofit_sing_up.order_manager, @ortofit_sing_up.mail_manager]
        calls:
            - [setTemplateEngine, [@templating.engine.twig]]
            - [setProcessRouteId, ["ortofit_sing_up_process"]]

